@echo off
echo Compiling...
javac -cp "lib\mysql-connector-j-9.7.0.jar" -d out src\dao\DBConnection.java src\model\Movie.java src\dao\MovieDAO.java src\dao\WatchlistDAO.java src\dao\UserDAO.java src\dao\ReviewDAO.java src\ui\Menu.java src\Main.java
echo Running...
java -cp "out;lib\mysql-connector-j-9.7.0.jar" Main
